mysite/autos/urls.py
from django.urls import path

from . import views

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = "autos"
urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name="auto_update"),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),

    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete', views.MakeDelete.as_view(), name='make_delete'),
]

# Note that make_ and auto_ give us uniqueness within this application

mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('cat/create/', views.CatCreate.as_view(), name="cat_create"),
    path('cat/<int:pk>/update/', views.CatUpdate.as_view(), name="cat_update"),
    path('cat/<int:pk>/delete/', views.CatDelete.as_view(), name="cat_delete"),

    path('breed/', views.BreedView.as_view(), name="breed_list"),
    path('breed/create/', views.BreedCreate.as_view(), name="breed_create"),
    path('breed/<int:pk>/update/', views.BreedUpdate.as_view(), name="breed_update"),
    path('breed/<int:pk>/delete/', views.BreedDelete.as_view(), name="breed_delete"),
]

mysite/mysite/urls.py
import os

from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.static import serve

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # login
    path('accounts/', include('django.contrib.auth.urls')),

    # home
    path('', TemplateView.as_view(template_name='home/main.html')),

    # apps
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

# serve static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')
urlpatterns += [
    url(
        r'^site(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class MakeUser(models.Model):
    first_name = models.CharField(
        max_length=100,
        help_text='First Name',
        validators=[MinLengthValidator(2, "Must be longer than 1 character")]
    )
    surname = models.CharField(
        max_length=100,
        help_text='Last Name',
        validators=[MinLengthValidator(2, "Must be longer than 1 character")]
    )
    email = models.EmailField()

    def __str__(self):
        return self.email


class AutoUser(models.Model):
    user = models.ForeignKey(MakeUser, on_delete=models.CASCADE, null=False)
    nickname = models.CharField(
        max_length=100,
        help_text="Nick Name",
        validators=[MinLengthValidator(2, "Must be longer than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)

    def __str__(self):
        return self.nickname

mysite/autos/forms.py
from django.forms import ModelForm

from .models import MakeUser


class MakeForm(ModelForm):
    class Meta:
        model = MakeUser
        fields = '__all__'

mysite/autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import MakeUser, AutoUser
from .forms import MakeForm


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        make_count = MakeUser.objects.all().count()
        auto_list = AutoUser.objects.all()
        context = {
            'make_count': make_count,
            'auto_list': auto_list,
        }
        return render(request, 'autos/auto_list.html', context)


class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        make_list = MakeUser.objects.all()
        context = {
            'make_list': make_list,
        }
        return render(request, 'autos/make_list.html', context)


# We use reverse_lazy() because we are in "constructor attribute" code  that is run before urls.py is completely loaded
class MakeCreate(LoginRequiredMixin, CreateView):
    model = MakeUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')


# Take the easy way out on the main table. These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields value in the constructor attributes
class AutoCreate(LoginRequiredMixin, CreateView):
    model = AutoUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')

    # template = 'autos/makeuser_form.html'
    # success_url = reverse_lazy('autos:index')

    # def get(self, request):
    #     form = MakeForm()
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, self.template, context)
    #
    # def post(self, request):
    #     form = MakeForm(request.POST)
    #     if not form.is_valid():
    #         context = {
    #             'form': form
    #         }
    #         return render(request, self.template, context)
    #     form.save()
    #     return redirect(self.success_url)


# MakeUpdate has code to implement the get-post-validate-store flow
# AutoUpdate (below) is doing the same thing with no code and no form by extending UpdateView
class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = MakeUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')

    # template = 'autos/makeuser_form.html'
    # success_url = reverse_lazy('autos:index')

    # def get(self, request, pk):
    #     make = get_object_or_404(self.model, pk=pk)
    #     form = MakeForm(instance=make)
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, self.template, context)
    #
    # def post(self, request, pk):
    #     make = get_object_or_404(self.model, pk=pk)
    #     form = MakeForm(request.POST, instance=make)
    #     if not form.is_valid():
    #         context = {
    #             'form': form
    #         }
    #         return render(request, self.template, context)
    #     form.save()
    #     return redirect(self.success_url)


class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = AutoUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')


# We use reverse_lazy rather than reverse in the class attributes because views.py is loaded by urls.py
# and in urls.py as_view() causes the constructor for the view class to run
# before urls.py has been completely loaded and urlpatterns has been processed.
class MakeDelete(LoginRequiredMixin, DeleteView):
    model = MakeUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')

    # template = 'autos/makeuser_confirm_delete.html'
    # success_url = reverse_lazy('autos:index')

    # def get(self, request, pk):
    #     make = get_object_or_404(self.model, pk=pk)
    #     # form = MakeForm(instance=make)
    #     context = {
    #         'make': make,
    #     }
    #     return render(request, self.template, context)
    #
    # def post(self, request, pk):
    #     make = get_object_or_404(self.model, pk=pk)
    #     make.delete()
    #     return redirect(self.success_url)


class AutoDelete(LoginRequiredMixin, DeleteView):
    model = AutoUser
    fields = '__all__'
    success_url = reverse_lazy('autos:index')

# References: https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

mysite/autos/templates/autos/auto_list.html
{% extends 'autos/base.html' %}

{% block content %}
    <h1>Users Detail List</h1>

    {% if auto_list  %}
        <table style="width:100%">
            <thead>
                <tr>
                    <th>Nick Name</th>
                    <th>User Information</th>
                    <th>Mileage</th>
                    <th>Comments</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for auto in auto_list %}
                <tr>
                    <td>{{ auto.nickname }}</td>
                    <td>{{ auto.user }}</td>
                    <td>{{ auto.mileage }} miles</td>
                    <td>{{ auto.comments }}</td>
                    <td><a href="{% url 'autos:auto_update' auto.id %}"><button type="button" class="btn btn-primary btn-sm">Update</button></a></td>
                    <td><a href="{% url 'autos:auto_delete' auto.id %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There is no user detail in the library.</p>
    {% endif %}

    <br>
    {% if make_count > 0 %}
        <p>
            <a href="{% url 'autos:auto_create' %}">Add user detail</a> |
            <a href="{% url 'autos:make_list' %}">Users list</a> ({{ make_count }})
        </p>
    {% else %}
        <p>Please add a user before you add detail. <a href="{% url 'autos:make_create' %}">Add a user</a></p>
    {% endif %}

{% endblock content %}

mysite/autos/templates/autos/autouser_confirm_delete.html
{% extends 'autos/base.html' %}

{% block content %}
    <h1>Delete User Detail</h1>

    <p>Are you sure you want to delete the detail?</p>
    <ul>
        <li>name: {{ autouser.user.first_name }} {{ autouser.user.surname }}</li>
        <li>email: {{ autouser.user.email }}</li>
        <li>nickname: {{ autouser.nickname }}</li>
        <li>mileage: {{ autouser.mileage }}</li>
        <li>comments: {{ autouser.comments }}</li>
    </ul>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'autos:index' %}' ; return false;" value="Cancel">
    </form>

{% endblock content %}

mysite/autos/templates/autos/autouser_form.html
{% extends 'autos/base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}

        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'autos:index' %}' ; return false;" value="Cancel">
    </form>

{% endblock content %}

mysite/autos/templates/autos/base.html
{% extends 'base_bootstrap.html' %}

{% block title %}
    Autos
{% endblock title%}

{% block content %} {% endblock content %}

mysite/autos/templates/autos/make_list.html
{% extends 'autos/base.html' %}

{% block content %}
    <h1>Users List</h1>

    {% if make_list %}
        <table style="width:100%">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Surname</th>
                    <th>Email</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for make in make_list %}
                <tr>
                    <td>{{ make.first_name }}</td>
                    <td>{{ make.surname }}</td>
                    <td>{{ make.email }}</td>
                    <td><a href="{% url 'autos:make_update' make.id %}"><button type="button" class="btn btn-primary btn-sm">Update</button></a></td>
                    <td><a href="{% url 'autos:make_delete' make.id %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There is no user in the library. <a href="{% url 'autos:make_create' %}">Add a user</a></p>
    {% endif %}

    <br>
    <p>
        <a href="{% url 'autos:make_create' %}">Add a user</a> |
        <a href="{% url 'autos:index' %}">Users detail list</a>
    </p>

{% endblock content %}

mysite/autos/templates/autos/makeuser_confirm_delete.html
{% extends 'autos/base.html' %}

{% block content %}
    <h1>Delete User</h1>

    <p>Are you sure you want to delete the user?</p>
    <ul>
        <li>name: {{ autouser.user.first_name }} {{ autouser.user.surname }}</li>
        <li>email: {{ autouser.user.email }}</li>
    </ul>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'autos:index' %}' ; return false;" value="Cancel">
    </form>

{% endblock content %}

mysite/autos/templates/autos/makeuser_form.html
{% extends 'autos/base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}

        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'autos:index' %}' ; return false;" value="Cancel">
    </form>

{% endblock content %}