mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('cat/create/', views.CatCreate.as_view(), name="cat_create"),
    path('cat/<int:pk>/update/', views.CatUpdate.as_view(), name="cat_update"),
    path('cat/<int:pk>/delete/', views.CatDelete.as_view(), name="cat_delete"),

    path('breed/', views.BreedView.as_view(), name="breed_list"),
    path('breed/create/', views.BreedCreate.as_view(), name="breed_create"),
    path('breed/<int:pk>/update/', views.BreedUpdate.as_view(), name="breed_update"),
    path('breed/<int:pk>/delete/', views.BreedDelete.as_view(), name="breed_delete"),
]

mysite/mysite/urls.py
import os

from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.static import serve

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # login
    path('accounts/', include('django.contrib.auth.urls')),

    # home
    path('', TemplateView.as_view(template_name='home/main.html')),

    # apps
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

# serve static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')
urlpatterns += [
    url(
        r'^site(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator


# Create your models here.

class Breed(models.Model):
    breed_name = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Must longer than 1")]
    )

    def __str__(self):
        return self.breed_name


class Cat(models.Model):
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, null=False)
    cat_name = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Must longer than 1")]
    )
    weight = models.FloatField()
    foods = models.CharField(max_length=200)

    def __str__(self):
        return self.cat_name

mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Breed, Cat


# Create your views here.

class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        template = ""
        breed_count = Breed.objects.all().count()
        cat_count = Cat.objects.all().count()
        cat_list = Cat.objects.all()
        cxt = {
            'breed_count': breed_count,
            'cat_count': cat_count,
            'cat_list': cat_list,
        }
        return render(request, 'cats/cat_list.html', cxt)


class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        cat_count = Cat.objects.all().count()
        breed_count = Breed.objects.all().count()
        breed_list = Breed.objects.all()
        cxt = {
            'cat_count': cat_count,
            'breed_count': breed_count,
            'breed_list': breed_list,
        }
        return render(request, 'cats/breed_list.html', cxt)


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:index')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:index')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = reverse_lazy('cats:index')


class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:bread_list')


class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:bread_list')


class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    success_url = reverse_lazy('cats:bread_list')

mysite/cats/templates/cats/base.html
{% extends 'base_bootstrap.html' %}

{% block title %} Cats {% endblock title %}

{% block content %} {% endblock content %}

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "cats/base.html" %}

{% block content %}
    <h1>Delete Breed</h1>

    <p>Are you sure you want to delete the breed: <b>{{ breed.breed_name }}</b>?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" value="Cancel" onclick="window.location='{% url 'cats:breed_list' %}'; return false">
    </form>
{% endblock content %}

mysite/cats/templates/cats/breed_form.html
{% extends "cats/base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location='{% url 'cats:breed_list' %}'; return false;">
    </form>

{% endblock content %}

mysite/cats/templates/cats/breed_list.html
{% extends "cats/base.html" %}

{% block content %}
    <h1>Breeds List</h1>

    {% if breed_list %}
        <ul>
            {% for breed in breed_list %}
                <li>{{ breed.breed_name }} (
                    <a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
                    <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>
                    )
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <br>
    <p>{{ breed_count }} breed{{ breed_count|pluralize }} in the <i>Breeds List</i>.</p>
    <p>
        <a href="{% url 'cats:breed_create' %}">Create New Breed</a> |
        <a href="{% url 'cats:index' %}">View Cats List ({{ cat_count }})</a>
    </p>


{% endblock content %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "cats/base.html" %}

{% block content %}
    <h1>Delete Cat</h1>

    <p>Are you sure you want to delete the cat?</p>
    <ul>
        <li>Breed: {{ cat.breed }}</li>
        <li>Cat name: {{ cat.cat_name }}</li>
        <li>Weight: {{ cat.weight }}</li>
        <li>Foods: {{ cat.foods }}</li>
    </ul>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" value="Cancel" onclick="window.location='{% url 'cats:index' %}'; return false">
    </form>
{% endblock content %}

mysite/cats/templates/cats/cat_form.html
{% extends 'cats/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location='{% url 'cats:index' %}'; return false;">
    </form>

{%  endblock content %}

mysite/cats/templates/cats/cat_list.html
{% extends "cats/base.html" %}

{% block content %}
    <h1>Cats List</h1>

    <!--
    if bread_count > 0:
        if cat_list:
            for cat in cat_list:
                display(cat)
        display("(cat_count) cat in the Cats List")
        display("create new cat" => cat_create, "view breed list (breed_count)" => breed_list)
    else:
        display("Pleas create breeds before create cats." => breed_create)

    -->
    {% if breed_count > 0 %}

        {% if cat_list %}
            <table style="width: 100%">
                <thead>
                    <tr>
                        <th>Breed Name</th><th>Cat Name</th><th>Weight</th><th>Foods</th>
                        <th>Update</th><th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cat in cat_list %}
                    <tr>
                        <td>{{ cat.breed }}</td><td>{{ cat.cat_name }}</td><td>{{ cat.weight }}</td><td>{{ cat.foods }}</td>
                        <td><a href="{% url 'cats:cat_update' cat.id %}"><button type="button" class="btn btn-sm">Update</button></a></td>
                        <td><a href="{% url 'cats:cat_delete' cat.id %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <br>
        <p>{{ cat_count }} cat{{ cat_count|pluralize }} in the <i>Cats List</i>.</p>
        <p>
            <a href="{% url 'cats:cat_create' %}">Create New Cat</a> |
            <a href="{% url 'cats:breed_list' %}">View Breeds List ({{ breed_count }})</a>
        </p>

    {% else %}
        <p>There is no cat or breed in the library! Please create breeds before create cats.</p>
        <p><a href="{% url 'cats:breed_create' %}">Create Breed</a></p>
    {% endif %}

{% endblock content %}