adlist/adlist/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    # home
    path('', include('home.urls')),  # Change to ads.urls

    # admin
    path('admin/', admin.site.urls),  # Keep

    # login
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # apps
    path('ads/', include('ads.urls'))
]

# Serve the static HTML
urlpatterns += [
    url(
        r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(settings.BASE_DIR, 'site'), 'show_indexes': True},
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(settings.BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(
        0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login)),
    )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

adlist/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='index'),
    path('ad/<int:pk>/', views.AdDetailView.as_view(), name='detail'),

    path('ad/create/', views.AdCreateView.as_view(), name='create'),
    path('ad/<int:pk>/update/', views.AdUpdateView.as_view(), name='update'),
    path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(), name='delete'),

    path('ad_picture/<int:pk>/', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),

    path('ad/<int:pk>/favorite/', views.AddFavoriteView.as_view(), name="ad_favorite"),
    path('ad/<int:pk>/unfavorite/', views.DeleteFavoriteView.as_view(), name="ad_unfavorite"),
]

adlist/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "greater than 2 characters")],
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        null=True,
    )
    text = models.TextField()

    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        related_name='comments_owned',
    )

    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Favorite',
        related_name='favorite_ads',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters.")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        else:
            return f"{self.text[:11]} ..."


class Favorite(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self):
        return f"{self.user.username} likes {self.ad.title[:11]}"

adlist/ads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib.humanize.templatetags.humanize import naturaltime

from .owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from .form import CreateForm, CommentForm
from .models import Ad, Comment, Favorite
from .utils import dump_queries


class AdListView(OwnerListView):
    model = Ad
    template_name = 'ads/ad_list.html'

    def get(self, request):
        # ad_list = Ad.objects.all().order_by('-updated_at')

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            favorites = [row['id'] for row in rows]

        str_val = request.GET.get("search", False)
        if str_val:
            # # Simple title-only search
            # objects = Post.objects.filter(title__contains=str_val).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(title__contains=str_val)
            query.add(Q(text__contains=str_val), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:]
        else:
            # try both versions with > 4 posts and watch the queries that happen
            ad_list = Ad.objects.all().order_by('-updated_at')[:]
            # objects = Ad.objects.select_related().all().order_by('-updated_at')[:]
        for ad in ad_list:
            ad.natural_created = naturaltime(ad.created_at)
            ad.natural_updated = naturaltime(ad.updated_at)
            if len(ad.text) > 50:
                ad.text_preview = ad.text[:50] + '...'
            else:
                ad.text_preview = ad.text

        ctx = {
            "ad_list": ad_list,
            "favorites": favorites,
            "search": str_val,
        }
        # dump_queries()    # check SQL queries
        return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk):
        ad = Ad.objects.get(id=pk)

        comments = Comment.objects.filter(ad=ad).order_by('-updated_at')
        comment_form = CommentForm()

        favorites = list()
        if request.user.is_authenticated:
            rows = request.user.favorite_ads.values('id')
            favorites = [row['id'] for row in rows]

        ctx = {
            'ad': ad,
            'comments': comments,
            'comment_form': comment_form,
            'favorites': favorites,
        }
        return render(request, self.template_name, ctx)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:index')

    def get(self, request):
        form = CreateForm()
        ctx = {
            'form': form,
        }
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = CreateForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {
                'form': form,
            }
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:index')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {
            'form': form,
        }
        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)
        if not form.is_valid():
            ctx = {
                'form': form,
            }
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()
        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    template_name = 'ads/ad_confirm_delete.html'
    success_url = reverse_lazy('ads:index')


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()
        return redirect(reverse('ads:detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_confirm_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:detail', args=[ad.id])


# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Add PK", pk)
        title = get_object_or_404(Ad, id=pk)
        try:
            Favorite(user=request.user, ad=title).save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Delete PK", pk)
        title = get_object_or_404(Ad, id=pk)
        try:
            Favorite.objects.get(user=request.user, ad=title).delete()
        except Favorite.DoesNotExist as e:
            pass
        return HttpResponse()

adlist/ads/templates/ads/ad_confirm_delete.html
{% extends 'base_bootstrap.html' %}

{% load humanize %}

{% block content %}
    <h1>Delete Ad</h1>

    <p>Are you sure you want to delete the ad?</p>
    <ul>
        <li>Title: {{ ad.title }}</li>
        <li>Price: {{ ad.price }}</li>
        <li>Text: {{ ad.text }}</li>
    </ul>
    <p>(created at: {{ ad.created_at|naturaltime }} | updated at: {{ ad.updated_at|naturaltime }})</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:index' %}'; return false">
    </form>

{% endblock content %}

adlist/ads/templates/ads/ad_detail.html
{% extends 'home/base_menu.html' %}

{% load humanize %}

{% block content %}

    <span style="float: end;">
        <p class="text-muted">
            created <i>{{ ad.created_at|naturaltime }}</i> |
            updated <i>{{ ad.updated_at|naturaltime }}</i> |

{#            edit or delete for owner #}
            {% if ad.owner == user %}
                by <i>me</i> |
                <a href="{% url 'ads:update' ad.id %}"><i class="fa fa-pencil"></i></a> |
                <a href="{% url 'ads:delete' ad.id %}"><i class="fa fa-trash"></i></a> |
            {% else %}
                by <i>{{ ad.owner }}</i> |
            {% endif %}

{#            favorite if login #}
            {% if user.is_authenticated %}
                <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                <a href="#" onclick="favAd('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }});return false;"
                    {% if ad.id not in favorites %} style="display: none;" {% endif %}
                    id="favorite_star_{{ad.id}}"
                >
                    <span class="fa-stack" style="vertical-align: middle;">
                        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                        <i class="fa fa-star-o fa-stack-1x"></i>
                    </span>
                </a>
                <!-- the second href -->
                <a href="#" onclick="favAd('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                    {% if ad.id in favorites %} style="display: none;" {% endif %}
                    id="unfavorite_star_{{ad.id}}"
                >
                    <span class="fa-stack" style="vertical-align: middle;">
                        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                        <i class="fa fa-star-o fa-stack-1x"></i>
                    </span>
                </a>
            {% endif %}
        </p>
    </span>

{#    Content #}
    <h1>{{ ad.title }}</h1>

    {% if ad.content_type %}
        <div class="container" >
            <img style="float: end; max-width: 50%; align-content: center" src="{% url 'ads:ad_picture' ad.id %}" alt="">
        </div>
    {% endif %}

    <br>
    <p>{{ ad.price }}</p>
    <p>{{ ad.text }}</p>

{#    comment text box to submit #}
    <br>
    <hr>
    <div class="container">
        {% if user.is_authenticated %}
            <br clear="all">
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'ads:comment_create' ad.id %}">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" value="Submit">
                <input type="submit" value="Back to Ads List" onclick="window.location.href='{% url 'ads:index' %}'; return false;">
            </form>
        {% endif %}
    </div>

{#    comments list #}
    <br>
    {% for comment in comments %}
        <hr>
        <div class="container">
            <p>{{ comment.text }}</p>
            <p class="small text-muted">
                created <i>{{ comment.created_at|naturaltime }}</i> |
                updated <i>{{ comment.updated_at|naturaltime }}</i> |
                {% if user == comment.owner %}
                    by <i>me</i> |
                    <a href="{% url 'ads:comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
                {% else %}
                    by <i>{{ comment.owner }}</i>
                {% endif %}
            </p>
        </div>
    {% endfor %}
    <hr>

    <div class="container">
        <br>
        <p><a href="{% url 'ads:index' %}">Back to Ads List</a></p>
    </div>

    <br>

{#    for favorite #}
    <script>
        function favAd(url, ad_id) {
            console.log('Requesting JSON');
            $.post(
                url, {}, function(rows){
                    console.log(url, 'finished');
                    $("#unfavorite_star_"+ad_id).toggle();
                    $("#favorite_star_"+ad_id).toggle();
                }
            ).fail(
                function(xhr) {
                    alert('Url failed with '+xhr.status+' '+url);
                }
            );
        }
    </script>
{% endblock content %}

adlist/ads/templates/ads/ad_form.html
{% extends 'base_bootstrap.html' %}

{% load crispy_forms_tags %}    {#https://django-crispy-forms.readthedocs.io/en/latest/#}

{% block content %}

    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}

        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:index' %}'; return false">
    </form>

    <!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
    <script>
    $("#upload_form").submit(
        function() {
            console.log('Checking file size');
            if (window.File && window.FileReader && window.FileList && window.Blob) {
                var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
                if (file && file.size > {{ form.max_upload_limit }} ) {
                    alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
                    return false;
                }
            }
        }
    );
    </script>
{% endblock content %}

adlist/ads/templates/ads/ad_list.html
{% extends 'home/base_menu.html' %}

{% block content %}

    <div style="float:right">
        <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
        <form>
            <label>
                <input type="text" placeholder="Search.." name="search" {% if search %} value="{{ search }}" {% endif %}>
            </label>
            <button type="submit"><i class="fa fa-search"></i></button>
            <a href="{% url 'ads:index' %}"><i class="fa fa-undo"></i></a>
        </form>
    </div>

    <h1>Ads List</h1>

    {% if ad_list %}
        <ul>
        {% for ad in ad_list %}
            <li>
                <p>
                    <a href="{% url 'ads:detail' ad.id %}">{{ ad.title }}</a>

                    {% if user.is_authenticated %}
                        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                        <a href="#" onclick="favAd('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }});return false;"
                            {% if ad.id not in favorites %} style="display: none;" {% endif %}
                            id="favorite_star_{{ad.id}}"
                        >
                            <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                            </span>
                        </a>
                        <!-- the second href -->
                        <a href="#" onclick="favAd('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                            {% if ad.id in favorites %} style="display: none;" {% endif %}
                            id="unfavorite_star_{{ad.id}}"
                        >
                            <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                            </span>
                        </a>
                    {% endif %}
                </p>
                <p class="small">{{ ad.text_preview }}</p>
                <p class="small text-muted">
                    created <i>{{ ad.created_at }}</i> |
                    updated <i>{{ ad.natural_updated }}</i> |
                    {% if ad.owner == user %}
                        by <i>me</i> |
                        <a href="{% url 'ads:update' ad.id %}"><i class="fa fa-pencil"></i></a> |
                        <a href="{% url 'ads:delete' ad.id %}"><i class="fa fa-trash"></i></a>
                    {% else %}
                        by <i>{{ ad.owner }}</i> |
                    {% endif %}
                </p>
            </li>
        {% endfor %}
        </ul>

    {% else %}
        <p>There is no ad in the database.</p>
    {% endif %}

    <script>
        function favAd(url, ad_id) {
            console.log('Requesting JSON');
            $.post(
                url, {}, function(rows){
                    console.log(url, 'finished');
                    $("#unfavorite_star_"+ad_id).toggle();
                    $("#favorite_star_"+ad_id).toggle();
                }
            ).fail(
                function(xhr) {
                    alert('Url failed with '+xhr.status+' '+url);
                }
            );
        }
    </script>

{% endblock content %}

adlist/ads/templates/ads/comment_confirm_delete.html
{% extends 'home/base_menu.html' %}

{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delet?</p>
    <p>{{ comment.text }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Yes, delete.">
        <a href="{% url 'ads:detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
    </form>

{% endblock content %}